package com.internation.info.dao;

import com.internation.info.model.QuestionRevert;
import com.internation.info.model.QuestionRevertExample.Criteria;
import com.internation.info.model.QuestionRevertExample.Criterion;
import com.internation.info.model.QuestionRevertExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class QuestionRevertSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String countByExample(QuestionRevertExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("questionrevert");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String deleteByExample(QuestionRevertExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("questionrevert");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String insertSelective(QuestionRevert record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("questionrevert");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getRevertMessage() != null) {
            sql.VALUES("revertMessage", "#{revertMessage,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getuId() != null) {
            sql.VALUES("uId", "#{uId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            sql.VALUES("questionId", "#{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionFloor() != null) {
            sql.VALUES("questionFloor", "#{questionFloor,jdbcType=INTEGER}");
        }
        
        if (record.getRevertFloor() != null) {
            sql.VALUES("revertFloor", "#{revertFloor,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String selectByExample(QuestionRevertExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("revertMessage");
        sql.SELECT("createTime");
        sql.SELECT("uId");
        sql.SELECT("questionId");
        sql.SELECT("questionFloor");
        sql.SELECT("revertFloor");
        sql.FROM("questionrevert");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        QuestionRevert record = (QuestionRevert) parameter.get("record");
        QuestionRevertExample example = (QuestionRevertExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("questionrevert");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getRevertMessage() != null) {
            sql.SET("revertMessage = #{record.revertMessage,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getuId() != null) {
            sql.SET("uId = #{record.uId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            sql.SET("questionId = #{record.questionId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionFloor() != null) {
            sql.SET("questionFloor = #{record.questionFloor,jdbcType=INTEGER}");
        }
        
        if (record.getRevertFloor() != null) {
            sql.SET("revertFloor = #{record.revertFloor,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("questionrevert");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("revertMessage = #{record.revertMessage,jdbcType=VARCHAR}");
        sql.SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("uId = #{record.uId,jdbcType=INTEGER}");
        sql.SET("questionId = #{record.questionId,jdbcType=INTEGER}");
        sql.SET("questionFloor = #{record.questionFloor,jdbcType=INTEGER}");
        sql.SET("revertFloor = #{record.revertFloor,jdbcType=INTEGER}");
        
        QuestionRevertExample example = (QuestionRevertExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    public String updateByPrimaryKeySelective(QuestionRevert record) {
        SQL sql = new SQL();
        sql.UPDATE("questionrevert");
        
        if (record.getRevertMessage() != null) {
            sql.SET("revertMessage = #{revertMessage,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getuId() != null) {
            sql.SET("uId = #{uId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            sql.SET("questionId = #{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionFloor() != null) {
            sql.SET("questionFloor = #{questionFloor,jdbcType=INTEGER}");
        }
        
        if (record.getRevertFloor() != null) {
            sql.SET("revertFloor = #{revertFloor,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    protected void applyWhere(SQL sql, QuestionRevertExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}