package com.internation.info.dao;

import com.internation.info.model.QuestionRevert;
import com.internation.info.model.QuestionRevertExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface QuestionRevertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @SelectProvider(type=QuestionRevertSqlProvider.class, method="countByExample")
    int countByExample(QuestionRevertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @DeleteProvider(type=QuestionRevertSqlProvider.class, method="deleteByExample")
    int deleteByExample(QuestionRevertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @Delete({
        "delete from questionrevert",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @Insert({
        "insert into questionrevert (id, revertMessage, ",
        "createTime, uId, ",
        "questionId, questionFloor, ",
        "revertFloor)",
        "values (#{id,jdbcType=INTEGER}, #{revertMessage,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{uId,jdbcType=INTEGER}, ",
        "#{questionId,jdbcType=INTEGER}, #{questionFloor,jdbcType=INTEGER}, ",
        "#{revertFloor,jdbcType=INTEGER})"
    })
    int insert(QuestionRevert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @InsertProvider(type=QuestionRevertSqlProvider.class, method="insertSelective")
    int insertSelective(QuestionRevert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @SelectProvider(type=QuestionRevertSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="revertMessage", property="revertMessage", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="uId", property="uId", jdbcType=JdbcType.INTEGER),
        @Result(column="questionId", property="questionId", jdbcType=JdbcType.INTEGER),
        @Result(column="questionFloor", property="questionFloor", jdbcType=JdbcType.INTEGER),
        @Result(column="revertFloor", property="revertFloor", jdbcType=JdbcType.INTEGER)
    })
    List<QuestionRevert> selectByExample(QuestionRevertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @Select({
        "select",
        "id, revertMessage, createTime, uId, questionId, questionFloor, revertFloor",
        "from questionrevert",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="revertMessage", property="revertMessage", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="uId", property="uId", jdbcType=JdbcType.INTEGER),
        @Result(column="questionId", property="questionId", jdbcType=JdbcType.INTEGER),
        @Result(column="questionFloor", property="questionFloor", jdbcType=JdbcType.INTEGER),
        @Result(column="revertFloor", property="revertFloor", jdbcType=JdbcType.INTEGER)
    })
    QuestionRevert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @UpdateProvider(type=QuestionRevertSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") QuestionRevert record, @Param("example") QuestionRevertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @UpdateProvider(type=QuestionRevertSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") QuestionRevert record, @Param("example") QuestionRevertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @UpdateProvider(type=QuestionRevertSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(QuestionRevert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionrevert
     *
     * @mbggenerated Sun May 06 14:56:00 CST 2018
     */
    @Update({
        "update questionrevert",
        "set revertMessage = #{revertMessage,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "uId = #{uId,jdbcType=INTEGER},",
          "questionId = #{questionId,jdbcType=INTEGER},",
          "questionFloor = #{questionFloor,jdbcType=INTEGER},",
          "revertFloor = #{revertFloor,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(QuestionRevert record);
}